sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zjw137zjw
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNXeyVesiH2URgRYjAj
    access-key-secret: KYeExPGd1vROPBmrhADLIcxAN7Htsk
    bucket-name: web-huaperion-tlias
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx7c5453f3eb45e6d9
    secret: 49cd5e3846cdd73133d1ce114b3e0c1d
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: http://79dea95a.r17.cpolar.top/notify/paySuccess
    refundNotifyUrl: http://79dea95a.r17.cpolar.top/notify/refundSuccess