sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zjw137zjw
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNXeyVesiH2URgRYjAj
    access-key-secret: KYeExPGd1vROPBmrhADLIcxAN7Htsk
    bucket-name: web-huaperion-tlias
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx7c5453f3eb45e6d9
    secret: 49cd5e3846cdd73133d1ce114b3e0c1d